<script type="text/javascript">
    //<![CDATA[
    function getStats() {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/adminhtml_cloudflare/stats') ?>', {
            method:     'post',
            parameters: {interval: $('cloudflare_stats_stats')[$('cloudflare_stats_stats').selectedIndex].value},
            onSuccess: function(transport){
				
				console.log(transport.responseText);
				
			
	            if (transport.responseText){
	            	if($('cloudflare_stats_table')){
		            	$('cloudflare_stats_table').remove();
	            	}
	                $('cloudflare_stats').insert(transport.responseText);
	            }else{
		            alert("Error in get statistic from CloudFare");

	            }
	            
	            
	            
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>