<script type="text/javascript">
    //<![CDATA[
    function unList() {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/adminhtml_cloudflare/iplist') ?>', {
            method:     'post',
            parameters: {ip: $$('#cloudflare_threat_threatip')[0].value, action : 'unlist'},
            onSuccess: function(transport){
				
				console.log(transport.responseText);
			
	            if (transport.responseText == 1){
	                alert("IP unlisted!");
	            }else{
		            alert("Error in unlist ip");

	            }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>